# Generated by Django 5.2.17 on 2026-08-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='category',
            field=models.CharField(default='AI Automation', max_length=100),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
