# Generated by Django 5.2.17 on 2026-08-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField()),
                ('pricing_info', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(default='settings', max_length=50)),
                ('features', models.JSONField(default=list)),
                ('display_order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
