# Generated by Django 5.2.17 on 2026-08-11 12:06

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_business_ids(apps, schema_editor):
    Appointment = apps.get_model('core', 'Appointment')
    Lead = apps.get_model('core', 'Lead')
    SecurityLog = apps.get_model('core', 'SecurityLog')
    Visitor = apps.get_model('core', 'Visitor')

    for appointment in Appointment.objects.all().iterator():
        appointment.appointment_id = f"APT-MIG-{appointment.pk:08d}"
        if appointment.status:
            appointment.status = appointment.status.upper()
        appointment.save(update_fields=['appointment_id', 'status'])

    for lead in Lead.objects.all().iterator():
        lead.lead_id = f"LD-MIG-{lead.pk:08d}"
        if lead.status:
            lead.status = lead.status.upper()
        if lead.priority:
            lead.priority = lead.priority.upper()
        lead.save(update_fields=['lead_id', 'status', 'priority'])

    for log in SecurityLog.objects.all().iterator():
        log.log_id = f"LOG-MIG-{log.pk:08d}"
        log.save(update_fields=['log_id'])

    for visitor in Visitor.objects.all().iterator():
        visitor.visitor_id = f"VIS-MIG-{visitor.pk:08d}"
        if not visitor.country or visitor.country == 'India':
            visitor.country = 'Unknown'
        if not visitor.country_code or visitor.country_code == 'India':
            visitor.country_code = 'Unknown'
        if visitor.country_type == 'India':
            visitor.country_type = 'Unknown'
        visitor.save(update_fields=['visitor_id', 'country', 'country_code', 'country_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visitor_country_type_visitor_visitor_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.CharField(default=core.models.subscriber_id_default, max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('source', models.CharField(default='Website', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNSUBSCRIBED', 'Unsubscribed'), ('BOUNCED', 'Bounced')], default='ACTIVE', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('visitor_session_id', models.CharField(blank=True, default='', max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='securitylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(default=core.models.appointment_id_default, max_length=40),
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visitor_session_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(default=core.models.lead_id_default, max_length=40),
        ),
        migrations.AddField(
            model_name='lead',
            name='visitor_session_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='browser',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='device',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='log_id',
            field=models.CharField(default=core.models.security_log_id_default, max_length=40),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='os',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=30),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='target_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='target_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country_code',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='visitor',
            name='landing_source',
            field=models.CharField(default='Direct', max_length=150),
        ),
        migrations.AddField(
            model_name='visitor',
            name='lead_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='visitor',
            name='pages_visited',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visitor',
            name='referrer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visitor',
            name='region',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='timezone',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_id',
            field=models.CharField(default=core.models.visitor_id_default, max_length=40),
        ),
        migrations.RunPython(populate_business_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(default=core.models.appointment_id_default, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(default=core.models.lead_id_default, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='log_id',
            field=models.CharField(default=core.models.security_log_id_default, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.CharField(default=core.models.visitor_id_default, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password changed'), ('PASSWORD_RESET', 'Password reset'), ('CREATE_USER', 'Create user'), ('UPDATE_USER', 'Update user'), ('DELETE_USER', 'Delete user'), ('CREATE_LEAD', 'Create lead'), ('UPDATE_LEAD', 'Update lead'), ('DELETE_LEAD', 'Delete lead'), ('CREATE_SUBSCRIBER', 'Create subscriber'), ('UPDATE_SUBSCRIBER', 'Update subscriber'), ('DELETE_SUBSCRIBER', 'Delete subscriber'), ('CREATE_APPOINTMENT', 'Create appointment'), ('UPDATE_APPOINTMENT', 'Update appointment'), ('DELETE_APPOINTMENT', 'Delete appointment'), ('CREATE_BLOG', 'Create blog'), ('UPDATE_BLOG', 'Update blog'), ('DELETE_BLOG', 'Delete blog'), ('CREATE_CASE_STUDY', 'Create case study'), ('UPDATE_CASE_STUDY', 'Update case study'), ('DELETE_CASE_STUDY', 'Delete case study'), ('CMS_UPDATE', 'CMS update')], max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='browser',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='country_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='device',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='device_model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='isp',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='location',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='os',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
