# Generated by Django 5.2.17 on 2026-08-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('results', models.TextField()),
                ('seo_title', models.CharField(blank=True, max_length=150, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('featured_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
