# Generated by Django 5.2.17 on 2026-08-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='client_link',
            field=models.URLField(blank=True, help_text='Optional live project or case study link', null=True),
        ),
    ]
