# Generated by Django 5.2.17 on 2026-08-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='External image fallback URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional - video guide ka Youtube link. Post ke body ke saath dikhega.', max_length=500, null=True),
        ),
    ]
