# Generated by Django 5.2.17 on 2026-08-10 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('profile_image', models.URLField()),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('skills', models.JSONField(default=list)),
                ('revenue', models.CharField(default='₹0', max_length=50)),
                ('leads_count', models.IntegerField(default=0)),
                ('attendance', models.CharField(default='100%', max_length=50)),
                ('kpi', models.CharField(default='5.0/5', max_length=50)),
                ('display_order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=150, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('email', models.CharField(default='Guest', max_length=150)),
                ('location', models.CharField(default='India', max_length=150)),
                ('isp', models.CharField(default='Telecom', max_length=150)),
                ('is_bot', models.BooleanField(default=False)),
                ('bot_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bot_category', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(default='Desktop', max_length=50)),
                ('device_model', models.CharField(default='PC', max_length=100)),
                ('browser', models.CharField(default='Chrome', max_length=50)),
                ('os', models.CharField(default='Windows', max_length=50)),
                ('entry_page', models.CharField(default='/', max_length=250)),
                ('current_page', models.CharField(default='/', max_length=250)),
                ('exit_page', models.CharField(default='/', max_length=250)),
                ('session_duration', models.IntegerField(default=0)),
                ('scroll_pct', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=1)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(default='Website', max_length=100)),
                ('status', models.CharField(default='new', max_length=50)),
                ('priority', models.CharField(default='normal', max_length=50)),
                ('lead_score', models.IntegerField(default=50)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(default='AI Audit', max_length=100)),
                ('meeting_type', models.CharField(default='AI Audit Consultation', max_length=100)),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(max_length=150)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
