# Generated by Django 5.2.17 on 2026-08-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teammember_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='country_type',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(default='Human', max_length=50),
        ),
    ]
